### PR TITLE
Fix/no quantifier assigned to self

### LINKED ISSUE #61: assigned to quantify praise that I received
currently on http://68.183.14.23/

discord handle: divine_comedian#5493

quantifying praise I noticed that somehow I was assigned to quantify praise that was given to me. this should be impossible that a quantifiers quantify themselves.

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #61 

This PR ensures that a quantifier is not assigned to any of their own praise (i.e. praise in which one of their UserAccounts is the receiver).

~However, it's not clear to me where / how quantifier Users are created, and thus I can't confirm if newly created Users are properly associated with their existing UserAccounts. For this to work properly, we will need to confirm that new Users are properly associated with their existing UserAccounts.~

### CODE REVIEW

**Comment by kristoferlund** [comment]
@mattyg, here are some details. Probably more than you asked for but I'm taking this opportunity to clarify some things to myself as well. 😄  

- A User is created when someone logs in to Praise by signing message in Metamask. One human = one User. Perhaps we should have named it Identity or something instead.
- A UserAccount is created or updated each time a new Praise is being registered in the system
  - UserAccounts are created from both the giver and the receiver
  - There does not have to be a User for there to be a UserAccount
- When a person activates their account by interacting with the Discord bot - `/praise-activate` - The UserAccount is linked to the User.
- A quantifier is any User with the role `QUANTIFIER`.
- All users marked as such make up the "quantifier pool".
- Quantifiers are assigned to all praise in a period using that assign algorithm that needs optimisation 🐌 

Some business rules in plain language:
- You have to activate your account in order to be able to praise
- You can praise anyone, no matter if they have a User or not
- In order for anyone to receive the rewards payout though, anyone has to activate their account, creating a User and linking it to their eth address.

**Comment by kristoferlund** [comment]
There are some details in the project doc on Notion:

https://fmckl.notion.site/The-new-Praise-system-0dcf8900af8d4a04a8b82c352cbb04ea

As well as in the (slightly dated) specs on HackMD:

https://hackmd.io/vQnoCnKlRIilLlROloBZHw
https://hackmd.io/mzwBnJqxRvGm-RjN-Zfd0A
https://hackmd.io/yHs9GqIVSb6pzkVJvW1Xvg
https://hackmd.io/FAp0POnMSlSRZOk1yS0YZw

I will (soon) look to update these to reflect present data models etc.

**Comment by mattyg** [comment]
@kristoferlund amazingly helpful thank you!

**Review by kristoferlund — APPROVED** [review]
Looks good!

**Pull request merged**
