### PR TITLE
Fix/highlight nav

### LINKED ISSUE #244: Highlight current page in Navs
Currently, the Navs in the sidebar and period pages do not have any visual indication of what page you're on.

Add a visual shading / background color change to indicate the page you're currently on.

### PR DESCRIPTION
**Pull request by Vyvy-vi**
closes #244 

This PR makes the navigation items change colour on selection.

### CODE REVIEW

**Review by mattyg — CHANGES_REQUESTED** [review]
Looks good!

My only request is can we make the colors different for the active NavItem vs the hovered NavItem?

What about: 
- on hover: bg-gray-100
- on active page: text-white, bg-gray-800

Or something like that

**Comment by Vyvy-vi** [comment]
sounds good to me 👍

**Comment by kristoferlund** [comment]
We need to have a chat about the benefit of highlighting the nav like this. When moving to subpages of main categories the highlight disappears which is.. unexpected behaviour I believe. And since it is difficult to determine for some pages which main "category" they belong to, praise detail page for instance, then it is questionable if highlighting adds any value where it is used.

**Comment by mattyg** [comment]
> We need to have a chat about the benefit of highlighting the nav like this. When moving to subpages of main categories the highlight disappears which is.. unexpected behaviour I believe. And since it is difficult to determine for some pages which main "category" they belong to, praise detail page for instance, then it is questionable if highlighting adds any value where it is used.

I think the only page that can be reached from multiple menu items is the Praise Detail -- otherwise the rest are sub-pages of a menu-item. 

I think you're right: a menu item should be "active" when on any of its sub-pages.

For the Praise Detail page I think it's fine to just not highlight any menu item.

**Comment by Vyvy-vi** [comment]
Q) So should we make an altered version of `NavItem` that doesn't have the highlights, for the PraiseDetail page?

**Comment by mattyg** [comment]
> Q) So should we make an altered version of `NavItem` that doesn't have the highlights, for the PraiseDetail page?

It's already not being highlighted, so no change necessary. My idea was we could display the NavItem in the sidebar as active if any of its "child" pages (in the navigation tree) are active.

But I think we just need to discuss it more before moving forward.

Anyway this is great vy, thank you! We can pick it up while you're on leave this month!

**Comment by kristoferlund** [comment]
> It's already not being highlighted, so no change necessary. My idea was we could display the NavItem in the sidebar as active if any of its "child" pages (in the navigation tree) are active.

Agree. `NavItem` is active if top level page or any of its subpages are active. 

We only need to provider a subtle signal which page the user is on, the dark gray `bg-gray-800` captures attention too much, let's go with `bg-gray-200` instead.

**Comment by mattyg** [comment]
I copied this branch to `fix/highlight-nav` so I could pick it up. So I had to open a new PR #396 -- closing this one.

**Pull request closed without merging**
